# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bitcoin Tirol
email: hello@bitcoin-tirol.at
description: >- # this means to ignore newlines until "baseurl:"
  Bitcoin Tirol ist eine Initiative mit dem Ziel Interessierte an 
  der Bitcoin-Blockchain-Technologie zu vernetzen, Wissen zu verbreiten 
  und ein Netzwerk von Experten zum Thema aufzubauen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bitcoin-tirol.at" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@opsec_roli"
github_username:  rolandschellhorn

future: true
timezone: Europe/Vienna

meta_theme_color: "#F29112"
twitter_site: "@Einundzwanzig_I"
twitter_title: "Bitcoin Tirol"
twitter_description: "Bitcoin Stammtisch Tirol Innsbruck - Bitcoin Austria"
twitter_image: ""
twitter_image_alt: "Bitcoin Stammtisch Tirol Innsbruck Image"

og_locale: "DE"
og_url: ""
og_title: "Bitcoin Stammtisch Tirol Innsbruck"
og_description: "Bitcoin Stammtisch Tirol Innsbruck - Bitcoin Austria"
og_image: ""
og_image_alt: "Bitcoin Stammtisch Tirol Innsbruck Image"
og_type: "website"
og_site_name: "Bitcoin Stammtisch Tirol Innsbruck"

social_twitter: "https://twitter.com/Einundzwanzig_I"
social_telegram: "https://t.me/joinchat/tEUQAr-3-m8xNWVk"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  events:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
